# Generated by Django 6.0.3 on 2026-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Uczeń'), ('TEACHER', 'Nauczyciel'), ('COLLEGIAN', 'Student'), ('OTHER', 'Inne')], default='STUDENT', max_length=10),
        ),
    ]
